export const categories = [
  {
    id: "nfl-superbowls",
    prompt: "Top 10 NFL teams by Super Bowl wins",
    sourceLabel: "Super Bowl wins",
    wordbank: [
      "Arizona Cardinals",
      "Atlanta Falcons",
      "Baltimore Ravens",
      "Buffalo Bills",
      "Carolina Panthers",
      "Chicago Bears",
      "Cincinnati Bengals",
      "Cleveland Browns",
      "Dallas Cowboys",
      "Denver Broncos",
      "Detroit Lions",
      "Green Bay Packers",
      "Houston Texans",
      "Indianapolis Colts",
      "Jacksonville Jaguars",
      "Kansas City Chiefs",
      "Las Vegas Raiders",
      "Los Angeles Chargers",
      "Los Angeles Rams",
      "Miami Dolphins",
      "Minnesota Vikings",
      "New England Patriots",
      "New Orleans Saints",
      "New York Giants",
      "New York Jets",
      "Philadelphia Eagles",
      "Pittsburgh Steelers",
      "San Francisco 49ers",
      "Seattle Seahawks",
      "Tampa Bay Buccaneers",
      "Tennessee Titans",
      "Washington Commanders"
    ],
    answers: [
      { name: "Pittsburgh Steelers", value: 6 },
      { name: "New England Patriots", value: 6 },
      { name: "San Francisco 49ers", value: 5 },
      { name: "Dallas Cowboys", value: 5 },
      { name: "Green Bay Packers", value: 4 },
      { name: "New York Giants", value: 4 },
      { name: "Kansas City Chiefs", value: 4 },
      { name: "Las Vegas Raiders", value: 3 },
      { name: "Washington Commanders", value: 3 },
      { name: "Denver Broncos", value: 3 }
    ]
  },
  {
    id: "population-2023",
    prompt: "Top 10 most populous countries (2023 estimates)",
    sourceLabel: "Population (millions)",
    wordbank: [
      "Argentina",
      "Australia",
      "Bangladesh",
      "Belgium",
      "Brazil",
      "Canada",
      "China",
      "Colombia",
      "Democratic Republic of the Congo",
      "Egypt",
      "Ethiopia",
      "France",
      "Germany",
      "India",
      "Indonesia",
      "Iran",
      "Italy",
      "Japan",
      "Kenya",
      "Mexico",
      "Nigeria",
      "Pakistan",
      "Philippines",
      "Russia",
      "South Africa",
      "South Korea",
      "Spain",
      "Turkey",
      "United Kingdom",
      "United States",
      "Vietnam"
    ],
    answers: [
      { name: "India", value: 1428 },
      { name: "China", value: 1425 },
      { name: "United States", value: 340 },
      { name: "Indonesia", value: 277 },
      { name: "Pakistan", value: 240 },
      { name: "Nigeria", value: 224 },
      { name: "Brazil", value: 216 },
      { name: "Bangladesh", value: 173 },
      { name: "Russia", value: 144 },
      { name: "Mexico", value: 129 }
    ]
  },
  {
    id: "highest-mountains",
    prompt: "Top 10 highest mountains above sea level",
    sourceLabel: "Height (m)",
    wordbank: [
      "Annapurna I",
      "Broad Peak",
      "Cho Oyu",
      "Dhaulagiri I",
      "Gasherbrum I",
      "Gasherbrum II",
      "K2",
      "Kangchenjunga",
      "Kangchenjunga West",
      "Lhotse",
      "Makalu",
      "Manaslu",
      "Mount Everest",
      "Nanga Parbat",
      "Shishapangma",
      "Trivor",
      "Gyachung Kang",
      "Kangchenjunga South",
      "Kangchenjunga Central",
      "Baintha Brakk"
    ],
    answers: [
      { name: "Mount Everest", value: 8849 },
      { name: "K2", value: 8611 },
      { name: "Kangchenjunga", value: 8586 },
      { name: "Lhotse", value: 8516 },
      { name: "Makalu", value: 8485 },
      { name: "Cho Oyu", value: 8188 },
      { name: "Dhaulagiri I", value: 8167 },
      { name: "Manaslu", value: 8163 },
      { name: "Nanga Parbat", value: 8126 },
      { name: "Annapurna I", value: 8091 }
    ]
  }
];
